### ISSUE TITLE
bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by ghost** [zerobyte-id/0byttt-whackdroid#1]
$ chmod +x install.sh
$ ./install.sh
bash: ./install.sh: /data/data/com.termux/files/usr/bin/bash^M: bad interpreter: No such file or directory

**Comment by zerobyte-id-bak** [comment]
Thanks for report:

Just remove LF with sed
`sed -i -e 's/\r$//' install.sh`

Before
`./install.sh`
